name: Foam Fire Extinguisher

on:
  schedule:
    # Ejecutar todos los d√≠as a las 3:00 AM
    - cron: '30-39 0-23/2 * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Call API
        run: |
          curl -X POST "https://extinguisherprices.com/api/save?q=Foam%20Fire%20Extinguisher" -H "Accept: application/json"
